driver:
  name: ec2

  # Use your chef-aws IAM creds
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY_ID'] || ENV['USER'] %>

  instance_type: c3.xlarge
  require_chef_omnibus: true

transport:
  username:

platforms:
  - name: centos-5.11
    transport:
      username: ec2-user
  # - name: centos-6.7
  #   run_list: yum-epel::default
  # - name: centos-7.1
  #   run_list: yum-epel::default
  # - name: debian-7.8
  #   run_list: apt::default
  # - name: debian-8.1
  #   run_list: apt::default
  # - name: freebsd-9.3
  #   run_list:
  #     - freebsd::portsnap
  #     - freebsd::pkgng
  # - name: freebsd-10.1
  #   run_list: freebsd::portsnap
  # - name: ubuntu-10.04
  #   run_list: apt::default
  # - name: ubuntu-12.04
  #   run_list: apt::default
  - name: ubuntu-14.04
    driver:
      image_id: ami-d93818e9
    transport:
      username: ubuntu

attribute_defaults: &attribute_defaults
  build_user:          shain
  build_user_group:    shain
  build_user_password: shain

suites:
  - name: gcc
    attributes:
      omnibus:
        <<: *attribute_defaults
        install_dir: /opt/omnibus-gcc
    run_list:
      - omnibus::default
