driver:
  name: vagrant
  forward_agent: yes
  customize:
    cpus: 4
    memory: 4096
  synced_folders:
    - ['..', '/vagrant/code']

provisioner:
  name: chef_zero
  attributes:
    vagrant:
      this_key_exists_so_we_have_a_vagrant_key: true
    omnibus:
      build_user: vagrant
      build_user_group: vagrant
      build_user_password: vagrant

platforms:
  - name: centos-6
    run_list: yum-epel::default

suites:
  - name: omnibus-gcc
    attributes:
      omnibus:
        toolchain_channel: stable
        toolchain_version: latest
        install_dir: /opt/omnibus-gcc
    run_list:
      - omnibus::default
