# Documentation available at https://expeditor.chef.io/docs/getting-started/
---
# Use a friendly alias which will make promotions easier
project:
  alias: omnibus-gcc

product_key:
  - omnibus-gcc

# Slack channel in Chef Software slack to send notifications about build failures, etc
slack:
  notify_channel:
    - releng-notify

pipelines:
  - omnibus/release
  - omnibus/adhoc:
      definition: .expeditor/release.omnibus.yml
      env:
        - ADHOC: true

# These actions are taken, in order they are specified, anytime a Pull Request is merged.
merge_actions:
  - built_in:bump_version:
      ignore_labels:
        - "Expeditor: Skip Version Bump"
        - "Expeditor: Skip All"
  - built_in:update_changelog:
      ignore_labels:
        - "Expeditor: Skip Changelog"
        - "Expeditor: Skip All"
  - trigger_pipeline:omnibus/release:
      ignore_labels:
        - "Expeditor: Skip Omnibus"
        - "Expeditor: Skip All"
      only_if: built_in:bump_version

subscriptions:
  - workload: artifact_published:stable:omnibus-gcc:*
    actions:
      - built_in:rollover_changelog
      - built_in:notify_chefio_slack_channels
